= Contributing to Simplify
Simplify is released under the link:LICENSE.txt[Apache 2.0 license]. If you would like to contribute something, or simply want to hack on the code this document should help you get started.

== Code of Conduct
This project adheres to the Contributor Covenant link:CODE_OF_CONDUCT.adoc[Code of Conduct]. By participating, you are expected to uphold this code.

== Using GitHub Issues
We use https://github.com/atsaug/simplify/issues[GitHub issues] to track bugs and enhancements. If you have a general usage question please ask on https://stackoverflow.com[Stack Overflow]. If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible.

== Code Conventions and Housekeeping
None of these is essential for a pull request, but they will all help. They can also be added after the original pull request but before a merge.

* If no-one else is using your branch, please rebase it against the current master (or other target branch in the main project)
* When writing a commit message please follow http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html[these conventions]

== Working with the Code
If you don't have an IDE preference we would recommend that you use http://eclipse.org[Eclipse] when working with the code. Other IDEs and tools should also work without issue.